/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.ShapesDAO;
import Models.Helper;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author miguel
 */
public class MainPanel extends javax.swing.JPanel {
    ShapesDAO shapes;
    Helper helper;
    int x1,y1,x2,y2;
    Image painting;

    public void setPainting(Image painting) {
        this.painting = painting;
    }

    /**
     * Creates new form MainPanel
     * @param shapes
     */
    public MainPanel(ShapesDAO shapes) {
        initComponents();
        this.shapes=shapes;       
    }

    public void setShapes(ShapesDAO shapes) {
        this.shapes = shapes;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
            
        if (painting != null) {
            System.out.println("Image Found");
            g.drawImage(painting, 0, 0, this);
        }   
        helper=new Helper(g);
        helper.draw(shapes);
    }

    public int getX1() {
        return x1;
    }

    public void setX1(int x1) {
        this.x1 = x1;
    }

    public int getY1() {
        return y1;
    }

    public void setY1(int y1) {
        this.y1 = y1;
    }

    public int getX2() {
        return x2;
    }

    public void setX2(int x2) {
        this.x2 = x2;
    }

    public int getY2() {
        return y2;
    }

    public void setY2(int y2) {
        this.y2 = y2;
    }
    
    public ShapesDAO getShapes() {
        return shapes;
    }

    public Helper getHelper() {
        return helper;
    }

    public JComboBox<String> getColorsComboBox() {
        return colorsComboBox;
    }

    public JButton getLoadDrawingButton() {
        return loadDrawingButton;
    }

    public JButton getLoadImageButton() {
        return loadImageButton;
    }

    public JButton getSaveDrawingButton() {
        return saveDrawingButton;
    }

    public JComboBox<String> getShapesComboBox() {
        return shapesComboBox;
    }

    public JButton getClearButton() {
        return clearButton;
    }   
    
    public JPanel getToolPanel() {
        return toolPanel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolPanel = new javax.swing.JPanel();
        shapesComboBox = new javax.swing.JComboBox<>();
        colorsComboBox = new javax.swing.JComboBox<>();
        loadImageButton = new javax.swing.JButton();
        loadDrawingButton = new javax.swing.JButton();
        saveDrawingButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        shapesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Line", "Square", "Rectangle", "Circle", "Ellipse" }));

        colorsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Yellow", "Red" }));

        loadImageButton.setText("Load Image");

        loadDrawingButton.setText("Load Drawing");

        saveDrawingButton.setText("Save Drawing");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolPanelLayout = new javax.swing.GroupLayout(toolPanel);
        toolPanel.setLayout(toolPanelLayout);
        toolPanelLayout.setHorizontalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shapesComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorsComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadImageButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadDrawingButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveDrawingButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        toolPanelLayout.setVerticalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(shapesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadDrawingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveDrawingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 295, Short.MAX_VALUE)
                .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
//        x1=evt.getX();
//        y1=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
//        x2=evt.getX();
//        y2=evt.getY();
//        aux=1;
//        repaint();
    }//GEN-LAST:event_formMouseReleased

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> colorsComboBox;
    private javax.swing.JButton loadDrawingButton;
    private javax.swing.JButton loadImageButton;
    private javax.swing.JButton saveDrawingButton;
    private javax.swing.JComboBox<String> shapesComboBox;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables

}
