/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author miguel
 */
public class ToolPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToolPanel
     */
    public ToolPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapeSelectionCombo = new javax.swing.JComboBox<>();
        ColorSelectionCombo = new javax.swing.JComboBox<>();
        loadDrawingButton = new javax.swing.JButton();
        saveDrawingButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        loadImageButton = new javax.swing.JButton();

        shapeSelectionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Line", "Square", "Rectangle", "Circle", "Ellipse" }));

        ColorSelectionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Yellow", "Red" }));

        loadDrawingButton.setText("Load Drawing");
        loadDrawingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDrawingButtonActionPerformed(evt);
            }
        });

        saveDrawingButton.setText("Save Drawing");

        clearButton.setText("Clear");

        loadImageButton.setText("Load Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shapeSelectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColorSelectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadImageButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadDrawingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveDrawingButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColorSelectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shapeSelectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)
                    .addComponent(loadImageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDrawingButton)
                    .addComponent(saveDrawingButton))
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadDrawingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDrawingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadDrawingButtonActionPerformed

    public JComboBox<String> getColorSelectionCombo() {
        return ColorSelectionCombo;
    }

    public JButton getClearButton() {
        return clearButton;
    }

    public JButton getLoadDrawingButton() {
        return loadDrawingButton;
    }

    public JButton getLoadImageButton() {
        return loadImageButton;
    }

    public JButton getSaveDrawingButton() {
        return saveDrawingButton;
    }

    public JComboBox<String> getShapeSelectionCombo() {
        return shapeSelectionCombo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColorSelectionCombo;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton loadDrawingButton;
    private javax.swing.JButton loadImageButton;
    private javax.swing.JButton saveDrawingButton;
    private javax.swing.JComboBox<String> shapeSelectionCombo;
    // End of variables declaration//GEN-END:variables
}
